=== bangsholt/napkinlaf/napkin/core/src/main/resources/net/sourceforge/napkinlaf/resources/templates/Template.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://napkinlaf.sf.net/sketch/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://napkinlaf.sf.net/sketch/"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="template">
        <xs:annotation>
            <xs:documentation>Describes a NapkinSketch image
                template</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element ref="clippingBounds"/>
                <xs:element ref="templateItem" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Definition of complex elements -->
    <xs:element name="clippingBounds">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="origin" type="point" minOccurs="0"/>
                <xs:element ref="dimensions"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="dimensions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="width" type="xs:positiveInteger"/>
                <xs:element name="height" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="templateItem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="drawStroke" type="xs:boolean" default="true"
                            minOccurs="0"/>
                <xs:element name="drawFill" type="xs:boolean" default="true"
                            minOccurs="0"/>
                <xs:element name="strokeWeight" type="positiveFloat"
                            minOccurs="0"/>
                <xs:element name="strokeColor" type="color" minOccurs="0"/>
                <xs:element name="fillColor" type="color" minOccurs="0"/>
                <xs:group ref="shape"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Definition of shape group and shape group elements -->
    <xs:group name="shape">
        <xs:choice>
            <xs:element ref="straightLine"/>
            <xs:element ref="quadLine"/>
            <xs:element ref="cubicLine"/>
            <xs:element ref="path"/>
        </xs:choice>
    </xs:group>
    <xs:element name="straightLine">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="start"/>
                <xs:element ref="end"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="quadLine">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="start"/>
                <xs:element ref="control"/>
                <xs:element ref="end"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cubicLine">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="start"/>
                <xs:element ref="control"/>
                <xs:element ref="control"/>
                <xs:element ref="end"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="path">
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="pathData" maxOccurs="unbounded"/>
                <xs:element name="close" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Definition of pathData and lineData groups -->
    <xs:group name="pathData">
        <xs:sequence>
            <xs:element ref="moveTo"/>
            <xs:group ref="lineData" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>
    <xs:group name="lineData">
        <xs:choice>
            <xs:element ref="lineTo"/>
            <xs:element ref="quadTo"/>
            <xs:element ref="cubicTo"/>
        </xs:choice>
    </xs:group>
    <!-- Definition of path elements -->
    <xs:element name="moveTo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="point"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="lineTo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="point"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="quadTo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="control"/>
                <xs:element ref="point"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cubicTo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="control"/>
                <xs:element ref="control"/>
                <xs:element ref="point"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Definition of simple data types -->
    <xs:simpleType name="positiveFloat">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Definition of complex data types, point and color -->
    <xs:complexType name="point">
        <xs:sequence>
            <xs:element name="x" type="xs:integer"/>
            <xs:element name="y" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="color">
        <xs:sequence>
            <xs:element name="r" type="xs:unsignedByte"/>
            <xs:element name="g" type="xs:unsignedByte"/>
            <xs:element name="b" type="xs:unsignedByte"/>
        </xs:sequence>
    </xs:complexType>
    <!-- Definition of point type elements -->
    <xs:element name="point" type="point"/>
    <xs:element name="start" type="point"/>
    <xs:element name="control" type="point"/>
    <xs:element name="end" type="point"/>
</xs:schema>

=== bangsholt/napkinlaf/trunk/napkin/src/net/sourceforge/napkinlaf/resources/templates/Directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns="http://napkinlaf.sf.net/sketch/"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://napkinlaf.sf.net/sketch Template.xsd">
    <!-- $Id: Directory.xml 293 2006-03-06 14:18:49Z kcrca $ -->
    <title>Directory</title>
    <description>A directory/folder</description>

    <clippingBounds>
        <dimensions>
            <width>19</width>
            <height>18</height>
        </dimensions>
    </clippingBounds>

    <templateItem>                <!-- folder tab -->
        <path>
            <moveTo>
                <point>
                    <x>1</x>
                    <y>4</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>3</x>
                    <y>2</y>
                </point>
            </lineTo>
            <lineTo>
                <point>
                    <x>7</x>
                    <y>2</y>
                </point>
            </lineTo>
            <lineTo>
                <point>
                    <x>9</x>
                    <y>4</y>
                </point>
            </lineTo>
        </path>
    </templateItem>

    <templateItem>                <!-- folder front -->
        <path>
            <moveTo>
                <point>
                    <x>14</x>
                    <y>5</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>1</x>
                    <y>5</y>
                </point>
            </lineTo>
            <lineTo>
                <point>
                    <x>1</x>
                    <y>15</y>
                </point>
            </lineTo>
            <lineTo>
                <point>
                    <x>15</x>
                    <y>15</y>
                </point>
            </lineTo>
            <lineTo>
                <point>
                    <x>15</x>
                    <y>5</y>
                </point>
            </lineTo>
            <close/>
        </path>
    </templateItem>

</template>

=== bangsholt/napkinlaf/trunk/napkin/src/edu/wpi/mqp/napkin/resources/UpFolder.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns="http://www.mqp.wpi.edu/napkin/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mqp.wpi.edu/napkin/ Template.xsd">
	<title>Up Folder</title>
	<description>Up</description>
	<clippingBounds>
		<dimensions>
			<width>19</width>
			<height>18</height>
		</dimensions>
	</clippingBounds>
	<!-- folder tab -->
	<templateItem>
		<drawStroke>true</drawStroke>
		<drawFill>true</drawFill>
		<strokeWeight>1</strokeWeight>
		<strokeColor>
			<r>0</r>
			<g>0</g>
			<b>0</b>
		</strokeColor>
		<fillColor>
			<r>255</r>
			<g>255</g>
			<b>128</b>
		</fillColor>
		<path>
			<moveTo>
				<point>
					<x>1</x>
					<y>4</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>3</x>
					<y>2</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>7</x>
					<y>2</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>9</x>
					<y>4</y>
				</point>
			</lineTo>
		</path>
	</templateItem>
	<!-- folder front -->
	<templateItem>
		<drawStroke>true</drawStroke>
		<drawFill>true</drawFill>
		<strokeWeight>1</strokeWeight>
		<strokeColor>
			<r>0</r>
			<g>0</g>
			<b>0</b>
		</strokeColor>
		<fillColor>
			<r>255</r>
			<g>255</g>
			<b>128</b>
		</fillColor>
		<path>
			<moveTo>
				<point>
					<x>14</x>
					<y>4</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>1</x>
					<y>4</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>1</x>
					<y>14</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>15</x>
					<y>14</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>15</x>
					<y>5</y>
				</point>
			</lineTo>
			<close/>
		</path>
	</templateItem>
	<!-- arrow head -->
	<templateItem>
		<drawStroke>true</drawStroke>
		<drawFill>true</drawFill>
		<strokeWeight>1</strokeWeight>
		<strokeColor>
			<r>0</r>
			<g>0</g>
			<b>0</b>
		</strokeColor>
		<fillColor>
			<r>0</r>
			<g>0</g>
			<b>0</b>
		</fillColor>
		<path>
			<moveTo>
				<point>
					<x>4</x>
					<y>8</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>6</x>
					<y>6</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>8</x>
					<y>8</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>4</x>
					<y>8</y>
				</point>
			</lineTo>
			<close/>
		</path>
	</templateItem>
	<!-- arrow tail -->
	<templateItem>
		<drawStroke>true</drawStroke>
		<drawFill>false</drawFill>
		<strokeWeight>1</strokeWeight>
		<strokeColor>
			<r>0</r>
			<g>0</g>
			<b>0</b>
		</strokeColor>
		<path>
			<moveTo>
				<point>
					<x>6</x>
					<y>9</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>6</x>
					<y>11</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>10</x>
					<y>11</y>
				</point>
			</lineTo>
		</path>
	</templateItem>
</template>

=== bangsholt/napkinlaf/napkin/src/edu/wpi/mqp/napkin/resources/Save.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns="http://www.mqp.wpi.edu/napkin/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mqp.wpi.edu/napkin/
Template.xsd">
	<title>Warning Icon</title>
	<description>warning icon</description>
	<clippingBounds>
		<dimensions>
			<width>24</width>
			<height>24</height>
		</dimensions>
	</clippingBounds>
	<!-- floppy disk body -->
	<templateItem>
		<drawStroke>true</drawStroke>
		<drawFill>true</drawFill>
		<strokeColor>
			<r>64</r>
			<g>64</g>
			<b>128</b>
		</strokeColor>
		<fillColor>
			<r>64</r>
			<g>64</g>
			<b>192</b>
		</fillColor>
		<path>
			<moveTo>
				<point>
					<x>1</x>
					<y>22</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>1</x>
					<y>2</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>21</x>
					<y>2</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>21</x>
					<y>22</y>
				</point>
			</lineTo>
			<close/>
		</path>
	</templateItem>
	<!-- floppy disk label -->
	<templateItem>
		<drawStroke>true</drawStroke>
		<drawFill>true</drawFill>
		<strokeColor>
			<r>192</r>
			<g>192</g>
			<b>192</b>
		</strokeColor>
		<fillColor>
			<r>255</r>
			<g>255</g>
			<b>255</b>
		</fillColor>
		<path>
			<moveTo>
				<point>
					<x>4</x>
					<y>12</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>4</x>
					<y>2</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>18</x>
					<y>2</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>18</x>
					<y>12</y>
				</point>
			</lineTo>
			<close/>
		</path>
	</templateItem>
	<!-- floppy disk label lines -->
	<templateItem>
		<drawStroke>true</drawStroke>
		<drawFill>false</drawFill>
		<strokeColor>
			<r>192</r>
			<g>192</g>
			<b>192</b>
		</strokeColor>
		<path>
			<moveTo>
				<point>
					<x>6</x>
					<y>4</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>16</x>
					<y>4</y>
				</point>
			</lineTo>
			<moveTo>
				<point>
					<x>6</x>
					<y>6</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>16</x>
					<y>6</y>
				</point>
			</lineTo>
			<moveTo>
				<point>
					<x>6</x>
					<y>8</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>16</x>
					<y>8</y>
				</point>
			</lineTo>
		</path>
	</templateItem>
	<!-- floppy disk metal slider depression -->
	<templateItem>
		<drawStroke>false</drawStroke>
		<drawFill>true</drawFill>
		<fillColor>
			<r>64</r>
			<g>64</g>
			<b>128</b>
		</fillColor>
		<path>
			<moveTo>
				<point>
					<x>6</x>
					<y>15</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>18</x>
					<y>15</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>18</x>
					<y>22</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>6</x>
					<y>22</y>
				</point>
			</lineTo>
			<close/>
		</path>
	</templateItem>
	<!-- floppy disk metal slider -->
	<templateItem>
		<drawStroke>false</drawStroke>
		<drawFill>true</drawFill>
		<strokeColor>
			<r>64</r>
			<g>64</g>
			<b>128</b>
		</strokeColor>
		<fillColor>
			<r>192</r>
			<g>192</g>
			<b>192</b>
		</fillColor>
		<path>
			<moveTo>
				<point>
					<x>7</x>
					<y>22</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>7</x>
					<y>15</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>15</x>
					<y>15</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>15</x>
					<y>22</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>7</x>
					<y>22</y>
				</point>
			</lineTo>
			<moveTo>
				<point>
					<x>8</x>
					<y>20</y>
				</point>
			</moveTo>
			<lineTo>
				<point>
					<x>10</x>
					<y>20</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>10</x>
					<y>16</y>
				</point>
			</lineTo>
			<lineTo>
				<point>
					<x>8</x>
					<y>16</y>
				</point>
			</lineTo>
			<close/>
		</path>
	</templateItem>
</template>

=== bangsholt/napkinlaf/napkin/src/napkin/resources/templates/DetailsView.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns="http://www.mqp.wpi.edu/napkin/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.mqp.wpi.edu/napkin/Template.xsd">
    <!-- $Id$ -->
    <title>filenew.svg</title>
    <description>filenew.svg</description>

    <clippingBounds>
        <dimensions>
            <width>19</width>
            <height>18</height>
        </dimensions>
    </clippingBounds>

    <templateItem>
        <drawStroke>true</drawStroke>
        <drawFill>false</drawFill>
        <strokeWeight>1</strokeWeight>
        <strokeColor>
            <r>0</r>
            <g>0</g>
            <b>0</b>
        </strokeColor>
        <fillColor>
            <r>0</r>
            <g>0</g>
            <b>0</b>
        </fillColor>
        <path>
            <moveTo>
                <point>
                    <x>3</x>
                    <y>3</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>3</x>
                    <y>3</y>
                </point>
            </lineTo>
            <moveTo>
                <point>
                    <x>5</x>
                    <y>3</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>11</x>
                    <y>3</y>
                </point>
            </lineTo>
            <moveTo>
                <point>
                    <x>13</x>
                    <y>3</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>16</x>
                    <y>3</y>
                </point>
            </lineTo>
        </path>
    </templateItem>

    <templateItem>
        <drawStroke>true</drawStroke>
        <drawFill>false</drawFill>
        <strokeWeight>1</strokeWeight>
        <strokeColor>
            <r>0</r>
            <g>0</g>
            <b>0</b>
        </strokeColor>
        <fillColor>
            <r>0</r>
            <g>0</g>
            <b>0</b>
        </fillColor>
        <path>
            <moveTo>
                <point>
                    <x>3</x>
                    <y>8</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>3</x>
                    <y>8</y>
                </point>
            </lineTo>
            <moveTo>
                <point>
                    <x>5</x>
                    <y>8</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>11</x>
                    <y>8</y>
                </point>
            </lineTo>
            <moveTo>
                <point>
                    <x>13</x>
                    <y>8</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>16</x>
                    <y>8</y>
                </point>
            </lineTo>
        </path>
    </templateItem>

    <templateItem>
        <drawStroke>true</drawStroke>
        <drawFill>false</drawFill>
        <strokeWeight>1</strokeWeight>
        <strokeColor>
            <r>0</r>
            <g>0</g>
            <b>0</b>
        </strokeColor>
        <fillColor>
            <r>0</r>
            <g>0</g>
            <b>0</b>
        </fillColor>
        <path>
            <moveTo>
                <point>
                    <x>3</x>
                    <y>13</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>3</x>
                    <y>13</y>
                </point>
            </lineTo>
            <moveTo>
                <point>
                    <x>5</x>
                    <y>13</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>11</x>
                    <y>13</y>
                </point>
            </lineTo>
            <moveTo>
                <point>
                    <x>13</x>
                    <y>13</y>
                </point>
            </moveTo>
            <lineTo>
                <point>
                    <x>16</x>
                    <y>13</y>
                </point>
            </lineTo>
        </path>
    </templateItem>

</template>
